# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{opentox-ruby}
  s.version = "2.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christoph Helma, Martin Guetlein, Andreas Maunz, Micha Rautenberg, David Vorgrimmler"]
  s.date = %q{2011-06-15}
  s.description = %q{Ruby wrapper for the OpenTox REST API (http://www.opentox.org)}
  s.email = %q{helma@in-silico.ch}
  s.executables = ["opentox-install-debian.sh", "opentox-install-ubuntu.sh"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "bin/opentox-install-debian.sh",
    "bin/opentox-install-ubuntu.sh",
    "lib/algorithm.rb",
    "lib/authorization.rb",
    "lib/compound.rb",
    "lib/config/config_ru.rb",
    "lib/dataset.rb",
    "lib/environment.rb",
    "lib/error.rb",
    "lib/feature.rb",
    "lib/helper.rb",
    "lib/model.rb",
    "lib/ontology.rb",
    "lib/opentox-ruby.rb",
    "lib/opentox.owl",
    "lib/opentox.rb",
    "lib/overwrite.rb",
    "lib/parser.rb",
    "lib/policy.rb",
    "lib/rest_client_wrapper.rb",
    "lib/serializer.rb",
    "lib/spork.rb",
    "lib/task.rb",
    "lib/templates/default_guest_policy.xml",
    "lib/templates/default_policy.xml",
    "lib/to-html.rb",
    "lib/transform.rb",
    "lib/validation.rb"
  ]
  s.homepage = %q{http://github.com/helma/opentox-ruby}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Ruby wrapper for the OpenTox REST API}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<emk-sinatra-url-for>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra-respond_to>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra-static-assets>, [">= 0"])
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
      s.add_runtime_dependency(%q<rack>, [">= 0"])
      s.add_runtime_dependency(%q<rack-contrib>, [">= 0"])
      s.add_runtime_dependency(%q<rack-flash>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<rubyzip>, [">= 0"])
      s.add_runtime_dependency(%q<roo>, [">= 0"])
      s.add_runtime_dependency(%q<spreadsheet>, [">= 0"])
      s.add_runtime_dependency(%q<google-spreadsheet-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<tmail>, [">= 0"])
      s.add_runtime_dependency(%q<rinruby>, [">= 0"])
      s.add_runtime_dependency(%q<ohm>, [">= 0"])
      s.add_runtime_dependency(%q<ohm-contrib>, [">= 0"])
      s.add_runtime_dependency(%q<SystemTimer>, [">= 0"])
      s.add_runtime_dependency(%q<rjb>, [">= 0"])
      s.add_runtime_dependency(%q<dm-core>, [">= 0"])
      s.add_runtime_dependency(%q<dm-serializer>, [">= 0"])
      s.add_runtime_dependency(%q<dm-timestamps>, [">= 0"])
      s.add_runtime_dependency(%q<dm-types>, [">= 0"])
      s.add_runtime_dependency(%q<dm-migrations>, [">= 0"])
      s.add_runtime_dependency(%q<dm-validations>, [">= 0"])
      s.add_runtime_dependency(%q<dm-sqlite-adapter>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 3"])
      s.add_runtime_dependency(%q<ruby-plot>, ["~> 0.4.0"])
      s.add_runtime_dependency(%q<statsample>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<emk-sinatra-url-for>, [">= 0"])
      s.add_dependency(%q<sinatra-respond_to>, [">= 0"])
      s.add_dependency(%q<sinatra-static-assets>, [">= 0"])
      s.add_dependency(%q<rest-client>, [">= 0"])
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<rack-contrib>, [">= 0"])
      s.add_dependency(%q<rack-flash>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rubyzip>, [">= 0"])
      s.add_dependency(%q<roo>, [">= 0"])
      s.add_dependency(%q<spreadsheet>, [">= 0"])
      s.add_dependency(%q<google-spreadsheet-ruby>, [">= 0"])
      s.add_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_dependency(%q<tmail>, [">= 0"])
      s.add_dependency(%q<rinruby>, [">= 0"])
      s.add_dependency(%q<ohm>, [">= 0"])
      s.add_dependency(%q<ohm-contrib>, [">= 0"])
      s.add_dependency(%q<SystemTimer>, [">= 0"])
      s.add_dependency(%q<rjb>, [">= 0"])
      s.add_dependency(%q<dm-core>, [">= 0"])
      s.add_dependency(%q<dm-serializer>, [">= 0"])
      s.add_dependency(%q<dm-timestamps>, [">= 0"])
      s.add_dependency(%q<dm-types>, [">= 0"])
      s.add_dependency(%q<dm-migrations>, [">= 0"])
      s.add_dependency(%q<dm-validations>, [">= 0"])
      s.add_dependency(%q<dm-sqlite-adapter>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 3"])
      s.add_dependency(%q<ruby-plot>, ["~> 0.4.0"])
      s.add_dependency(%q<statsample>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<emk-sinatra-url-for>, [">= 0"])
    s.add_dependency(%q<sinatra-respond_to>, [">= 0"])
    s.add_dependency(%q<sinatra-static-assets>, [">= 0"])
    s.add_dependency(%q<rest-client>, [">= 0"])
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<rack-contrib>, [">= 0"])
    s.add_dependency(%q<rack-flash>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rubyzip>, [">= 0"])
    s.add_dependency(%q<roo>, [">= 0"])
    s.add_dependency(%q<spreadsheet>, [">= 0"])
    s.add_dependency(%q<google-spreadsheet-ruby>, [">= 0"])
    s.add_dependency(%q<yajl-ruby>, [">= 0"])
    s.add_dependency(%q<tmail>, [">= 0"])
    s.add_dependency(%q<rinruby>, [">= 0"])
    s.add_dependency(%q<ohm>, [">= 0"])
    s.add_dependency(%q<ohm-contrib>, [">= 0"])
    s.add_dependency(%q<SystemTimer>, [">= 0"])
    s.add_dependency(%q<rjb>, [">= 0"])
    s.add_dependency(%q<dm-core>, [">= 0"])
    s.add_dependency(%q<dm-serializer>, [">= 0"])
    s.add_dependency(%q<dm-timestamps>, [">= 0"])
    s.add_dependency(%q<dm-types>, [">= 0"])
    s.add_dependency(%q<dm-migrations>, [">= 0"])
    s.add_dependency(%q<dm-validations>, [">= 0"])
    s.add_dependency(%q<dm-sqlite-adapter>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 3"])
    s.add_dependency(%q<ruby-plot>, ["~> 0.4.0"])
    s.add_dependency(%q<statsample>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

